[package]
name = "db_client"
version = "0.1.0"
edition = "2021"

[dependencies]
qdrant-client = "1.10.2"
tokio = { version = "1.39.1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
clap = { version = "4.5.11", features = ["derive"] }
serde_json = "1.0.120"
